#!/bin/bash

# ORDER OF ARGUMENTS: GERMLINE/SOMATIC, NO OF JOBS, BAM / (NORMAL, TUMOUR), REFERENCE FASTA, RUN DIR
MANTA_DIR='/tools/manta-1.5.0.centos6_x86_64//bin'

$MANTA_DIR/configManta.py \
    --normalBam $2 \
    --tumorBam $3 \
    --referenceFasta $4 \
    --runDir $5
python $5/runWorkflow.py -m local -j $1
