#!/bin/bash

# ORDER OF ARGUMENTS: GERMLINE/SOMATIC, NO OF JOBS, BAM / (NORMAL, TUMOUR), REFERENCE FASTA, RUN DIR
MANTA_DIR='/tools/manta-1.5.0.centos6_x86_64//bin'

if [ $1 == 'germline' ]
then
	$MANTA_DIR/configManta.py \
	    --bam $3 \
	    --referenceFasta $4 \
	    --runDir $5
	python $5/runWorkflow.py -m local -j $2

elif [ $1 == 'somatic' ]
then
	$MANTA_DIR/configManta.py \
	    --normalBam $3 \
	    --tumorBam $4 \
	    --referenceFasta $5 \
	    --runDir $6
	python $6/runWorkflow.py -m local -j $2
fi
